# -*- coding: utf-8 -*-
"""JoinCode.ipynb의 사본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DWWzfO9LButFP1GlOHgeVJPJGqQ_uG_O
"""

import pandas as pd
from google.colab import files

# 1. 엑셀 파일 업로드
uploaded = files.upload()

# 2. 업로드한 파일 이름 가져오기
file_name = list(uploaded.keys())[0]

print("업로드한 파일:", file_name)

# 3. 엑셀 파일에서 두 시트 읽기
place_df = pd.read_excel(file_name, sheet_name="장소정보")
recommend_df = pd.read_excel(file_name, sheet_name="추천정보")

# 4. 원본 데이터 확인
print("장소정보 시트")
display(place_df)

print("추천정보 시트")
display(recommend_df)

# 5. place_id를 기준으로 두 데이터프레임 조인
merged_df = pd.merge(
    recommend_df,
    place_df,
    on="place_id",
    how="left"
)

# 6. 조인 결과 확인
print("조인 결과")
display(merged_df)
